#!/usr/bin/env node
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import {
  DICE_SHAPES,
  createAtlasLayout,
  renderManifest,
  renderCleanTemplateSvg,
  renderMaskSvg,
  renderPromptPack,
  renderTemplateSvg,
  validateAtlas,
} from './dice-atlas.mjs'

const args = parseArgs(process.argv.slice(2))
const outputDir = path.resolve(args.out ?? 'public/artist-resources/imagegen-uv')
const assetDir = path.join(outputDir, 'assets')
const shapes = args.shape ? [args.shape] : DICE_SHAPES
const size = args.size ? Number(args.size) : undefined

await mkdir(assetDir, { recursive: true })

const generated = []

for (const shape of shapes) {
  const layout = createAtlasLayout(shape, { size })
  const validation = validateAtlas(layout)
  if (!validation.valid) {
    throw new Error(`${shape} atlas is invalid:\n${validation.errors.join('\n')}`)
  }

  const templatePath = path.join(assetDir, `${shape}-uv-template.svg`)
  const cleanTemplatePath = path.join(assetDir, `${shape}-uv-clean-template.svg`)
  const maskPath = path.join(assetDir, `${shape}-uv-mask.svg`)
  const manifestPath = path.join(assetDir, `${shape}-uv-manifest.json`)
  const promptPath = path.join(outputDir, `${shape}-prompt-pack.md`)

  await writeFile(templatePath, renderTemplateSvg(layout), 'utf8')
  await writeFile(cleanTemplatePath, renderCleanTemplateSvg(layout), 'utf8')
  await writeFile(maskPath, renderMaskSvg(layout), 'utf8')
  await writeFile(manifestPath, `${JSON.stringify(renderManifest(layout), null, 2)}\n`, 'utf8')
  await writeFile(promptPath, renderPromptPack(layout, { material: args.material }), 'utf8')

  generated.push({ shape, templatePath, cleanTemplatePath, maskPath, manifestPath, promptPath })
}

const index = [
  '# Daisu ImageGen UV Assets',
  '',
  'Generated by `npm run generate:imagegen-uv`.',
  '',
  '| Shape | Clean Template | Labeled Guide | Mask | Manifest | Prompt Pack |',
  '|---|---|---|---|---|---|',
  ...generated.map((item) => {
    return `| ${item.shape} | [clean](assets/${item.shape}-uv-clean-template.svg) | [guide](assets/${item.shape}-uv-template.svg) | [mask](assets/${item.shape}-uv-mask.svg) | [manifest](assets/${item.shape}-uv-manifest.json) | [prompt](${item.shape}-prompt-pack.md) |`
  }),
  '',
  '## Canonical Numbered D20 Image-to-Image Proof',
  '',
  '- [Numbered mesh guide](d20-imagegen/d20-numbered-mesh-guide.png)',
  '- [ImageGen edit target](d20-imagegen/d20-imagegen-input.png)',
  '- [Mesh UV manifest](d20-imagegen/d20-mesh-uv-manifest.json)',
  '- [Exact edge-aligned built-in ImageGen prompt](d20-imagegen/d20-imagegen-edge-aligned-prompt.md)',
  '- [Generated edge-aligned antique-gold and blue-enamel albedo](d20-imagegen/antique-gold-blue-enamel-imagegen-v2-edge-aligned.png)',
  '- [Derived edge-aligned embossed-detail normal map](d20-imagegen/antique-gold-blue-enamel-normal-v2-edge-aligned.png)',
  '',
].join('\n')

await writeFile(path.join(outputDir, 'INDEX.md'), index, 'utf8')

console.log(`Generated ${generated.length} ImageGen UV atlas set(s) in ${path.relative(process.cwd(), outputDir)}`)

function parseArgs(argv) {
  const parsed = {}
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (!arg.startsWith('--')) continue
    const key = arg.slice(2)
    const next = argv[i + 1]
    if (!next || next.startsWith('--')) {
      parsed[key] = true
    } else {
      parsed[key] = next
      i++
    }
  }
  return parsed
}
